export const TYPES = {
  // Infrastructure
  EnvConfig: Symbol.for('EnvConfig'),
  DrizzleDatabase: Symbol.for('DrizzleDatabase'),
  ILogger: Symbol.for('ILogger'),
  IPasswordHasher: Symbol.for('IPasswordHasher'),
  ITokenService: Symbol.for('ITokenService'),

  // Repositories
  IUserRepository: Symbol.for('IUserRepository'),
  IRoleRepository: Symbol.for('IRoleRepository'),
  IPermissionRepository: Symbol.for('IPermissionRepository'),
  IRefreshTokenRepository: Symbol.for('IRefreshTokenRepository'),
  IAuthTokenRepository: Symbol.for('IAuthTokenRepository'),
  IAuditRepository: Symbol.for('IAuditRepository'),
  ICveRepository: Symbol.for('ICveRepository'),
  ISyncStateRepository: Symbol.for('ISyncStateRepository'),
  ISyncJobQueue: Symbol.for('ISyncJobQueue'),
  IAssetRepository: Symbol.for('IAssetRepository'),
  IVulnRepository: Symbol.for('IVulnRepository'),
  IAlertRepository: Symbol.for('IAlertRepository'),
  IIntelRepository: Symbol.for('IIntelRepository'),
  IReportRepository: Symbol.for('IReportRepository'),
  ICompanyRepository: Symbol.for('ICompanyRepository'),
  IChannelDispatcher: Symbol.for('IChannelDispatcher'),

  // Application services
  EffectivePermissionService: Symbol.for('EffectivePermissionService'),
  AuditService: Symbol.for('AuditService'),
  SessionService: Symbol.for('SessionService'),
  CatalogBootstrapService: Symbol.for('CatalogBootstrapService'),
  MatchAssetsService: Symbol.for('MatchAssetsService'),
  ProductCatalogService: Symbol.for('ProductCatalogService'),
  AlertEvaluatorService: Symbol.for('AlertEvaluatorService'),
  AlertUseCases: Symbol.for('AlertUseCases'),
  IntelUseCases: Symbol.for('IntelUseCases'),
  ReportService: Symbol.for('ReportService'),
  ReportUseCases: Symbol.for('ReportUseCases'),

  // Use cases - auth
  LoginUseCase: Symbol.for('LoginUseCase'),
  RefreshSessionUseCase: Symbol.for('RefreshSessionUseCase'),
  LogoutUseCase: Symbol.for('LogoutUseCase'),
  GetMeUseCase: Symbol.for('GetMeUseCase'),
  ChangePasswordUseCase: Symbol.for('ChangePasswordUseCase'),
  GetAuthTokenInfoUseCase: Symbol.for('GetAuthTokenInfoUseCase'),
  RegisterWithInviteUseCase: Symbol.for('RegisterWithInviteUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),

  // Use cases - users
  ListUsersUseCase: Symbol.for('ListUsersUseCase'),
  GetUserUseCase: Symbol.for('GetUserUseCase'),
  InviteUserUseCase: Symbol.for('InviteUserUseCase'),
  CreateUserUseCase: Symbol.for('CreateUserUseCase'),
  UpdateUserUseCase: Symbol.for('UpdateUserUseCase'),
  DeleteUserUseCase: Symbol.for('DeleteUserUseCase'),
  SetUserPermissionOverridesUseCase: Symbol.for('SetUserPermissionOverridesUseCase'),
  GetUserEffectivePermissionsUseCase: Symbol.for('GetUserEffectivePermissionsUseCase'),
  IssuePasswordResetUseCase: Symbol.for('IssuePasswordResetUseCase'),
  RevokeUserSessionsUseCase: Symbol.for('RevokeUserSessionsUseCase'),
  ListUserSessionsUseCase: Symbol.for('ListUserSessionsUseCase'),
  RevokeUserSessionUseCase: Symbol.for('RevokeUserSessionUseCase'),

  // Use cases - roles / permissions / audit
  ListRolesUseCase: Symbol.for('ListRolesUseCase'),
  GetRoleUseCase: Symbol.for('GetRoleUseCase'),
  CreateRoleUseCase: Symbol.for('CreateRoleUseCase'),
  UpdateRoleUseCase: Symbol.for('UpdateRoleUseCase'),
  DeleteRoleUseCase: Symbol.for('DeleteRoleUseCase'),
  ListPermissionsUseCase: Symbol.for('ListPermissionsUseCase'),
  ListAuditLogUseCase: Symbol.for('ListAuditLogUseCase'),

  // Use cases - CVE / sync
  SearchCvesUseCase: Symbol.for('SearchCvesUseCase'),
  GetCveUseCase: Symbol.for('GetCveUseCase'),
  GetCveStatsUseCase: Symbol.for('GetCveStatsUseCase'),
  GetSyncStatusUseCase: Symbol.for('GetSyncStatusUseCase'),
  RequestSyncUseCase: Symbol.for('RequestSyncUseCase'),

  // Use cases - inventory / vulnerabilities
  ListAssetsUseCase: Symbol.for('ListAssetsUseCase'),
  GetAssetUseCase: Symbol.for('GetAssetUseCase'),
  CreateAssetUseCase: Symbol.for('CreateAssetUseCase'),
  UpdateAssetUseCase: Symbol.for('UpdateAssetUseCase'),
  DeleteAssetUseCase: Symbol.for('DeleteAssetUseCase'),
  ImportAssetsUseCase: Symbol.for('ImportAssetsUseCase'),
  ListImportsUseCase: Symbol.for('ListImportsUseCase'),
  ListVulnsUseCase: Symbol.for('ListVulnsUseCase'),
  ListCveAssetsUseCase: Symbol.for('ListCveAssetsUseCase'),
  SetVulnStatusUseCase: Symbol.for('SetVulnStatusUseCase'),
  RematchVulnsUseCase: Symbol.for('RematchVulnsUseCase'),
  CheckSoftwareUseCase: Symbol.for('CheckSoftwareUseCase'),
  SoftwareCatalogUseCases: Symbol.for('SoftwareCatalogUseCases'),

  // HTTP
  AuthMiddleware: Symbol.for('AuthMiddleware'),
  AuthController: Symbol.for('AuthController'),
  AuthRouter: Symbol.for('AuthRouter'),
  UserController: Symbol.for('UserController'),
  UserRouter: Symbol.for('UserRouter'),
  RoleController: Symbol.for('RoleController'),
  RoleRouter: Symbol.for('RoleRouter'),
  AuditController: Symbol.for('AuditController'),
  AuditRouter: Symbol.for('AuditRouter'),
  CveController: Symbol.for('CveController'),
  CveRouter: Symbol.for('CveRouter'),
  SyncController: Symbol.for('SyncController'),
  SyncRouter: Symbol.for('SyncRouter'),
  InventoryController: Symbol.for('InventoryController'),
  InventoryRouter: Symbol.for('InventoryRouter'),
  VulnController: Symbol.for('VulnController'),
  VulnRouter: Symbol.for('VulnRouter'),
  AlertController: Symbol.for('AlertController'),
  AlertRouter: Symbol.for('AlertRouter'),
  IntelController: Symbol.for('IntelController'),
  IntelRouter: Symbol.for('IntelRouter'),
  ReportController: Symbol.for('ReportController'),
  ReportRouter: Symbol.for('ReportRouter'),
  CompanyUseCases: Symbol.for('CompanyUseCases'),
  CompanyController: Symbol.for('CompanyController'),
  CompanyRouter: Symbol.for('CompanyRouter'),
} as const;
